config/routes.rb
Rails.application.routes.draw do
  get 'employees/new'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
  get '/new', to: 'employees#new'
  resources :employees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
before_save :downcase_email

validates :name, presence: true, length: { maximum: 50 }
validates :dob, presence: true
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, length: { maximum: 128 }, 
    format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
validates :address, presence: true, length: { maximum: 256 }
validates :gender, presence: true
validates :job_id, presence: true, length: { maximum: 5 }, 
    numericality: { only_integer: true }


private
    def downcase_email
        self.email = email.downcase
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def index
    @employees = Employee.paginate(page: params[:page])
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def new
    @employee = Employee.new
  end
  
  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      flash[:success] = "Employee Successfully Added"
      redirect_to @employee
    else
      render 'new'
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      flash[:success] = "Employee Details Updated Successful"
      redirect_to @employee
    else
      render 'edit'
    end
  end

  def destroy
    Employee.find(params[:id]).destroy
    flash[:success] = "Employee Deleted"
    redirect_to employees_url 
  end

  private

    def employee_params
      params.require(:employee).permit(:name, :email, :dob, :address, 
        :gender, :job_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def full_title(page_title = '')
        base_title = "Employee Management System"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
    def  gravatar_for(user, options = { size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/employees/_employee.html.erb
<tr class="clickable-row" data-href="<%= employee_path(employee) %>" >
    <td><%= employee.id %></td>
    <td><%= gravatar_for employee, size: 45 %></td>
    <td><%= link_to employee.name, employee %></td>
    <td><%= link_to employee.email, employee %></td>
    <td><%= link_to employee.gender, employee %></td>
    <td><%= link_to employee.dob, employee %></td>
    <td><%= link_to employee.job_id, employee %></td>
    <td><%= link_to "Delete", employee, method: :delete, data: { confirm: "Are You Sure?"} %></td>
    <td><%= link_to "Edit", edit_employee_path(employee) %></td>
</tr>

app/views/employees/edit.html.erb
<% provide(:title, "Update")%>
<h1>Update Employee Details</h1>

<div class="row">
    <div class ="col-md-6 col-md-offset-3">
        <%= form_for(@employee) do |f|%>

            <%= render 'shared/error_messages' %>
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>

            <%= f.label :dob, "Date of Birth "%>
            <%= f.date_field :dob, class: "form-control" %>

            <%= f.label :email %>
            <%= f.text_field :email, class: "form-control" %>

            <%= f.label :address %>
            <%= f.text_area :address, class: "form-control" %>

            <%= f.label :gender %>
            <%= f.select :gender, ['Female','Male'], class: "form-control" %>

            <%= f.label :job_id, "Job ID"%>
            <%= f.text_field :job_id, class: "form-control" %>

            <%= f.submit "Update Details", class: "btn btn-primary "%>
        <% end %>
    </div>
</div>

app/views/employees/index.html.erb
<% provide(:title, "Employees")%>

<h1>All Employees</h1>

<%= will_paginate %>
<table class="table table-stribed">
  <thead>
    <tr>
      <th class="text-center" >id</th>
      <th class="text-center" >Avatar</th>
      <th class="text-center">Name</th>
      <th class="text-center">Email</th>
      <th class="text-center" >Gender</th>
      <th class="text-center" >Date of Birth</th>
      <th class="text-center" >Job Id</th>
    </tr>
  </thead>
  <tbody>
        <%= render @employees %>
   </tbody>
</table>
<%= will_paginate %>

app/views/employees/new.html.erb
<% provide(:title, "Create")%>
<h1>New Employees</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@employee, url: new_path) do |f|%>

            <%= render 'shared/error_messages' %>
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>

            <%= f.label :dob, "Date of Birth "%>
            <%= f.date_field :dob, class: "form-control" %>

            <%= f.label :email %>
            <%= f.text_field :email, class: "form-control" %>

            <%= f.label :address %>
            <%= f.text_area :address, class: "form-control" %>

            <%= f.label :gender %>
            <%= f.select :gender, ['Female','Male'], class: "form-control" %>

            <%= f.label :job_id, "Job ID"%>
            <%= f.text_field :job_id, class: "form-control" %>

            <%= f.submit "Create Employee", class: "btn btn-primary "%>
        <% end %>
    </div>
</div>

app/views/employees/show.html.erb
<% provide(:title, @employee.name)%>

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6">
                <div class="row">
                    <div class="col-sm-6 col-md-4">
                        <%= gravatar_for(@employee, size: 150) %>
                <!--        <img src="http://placehold.it/380x500" alt="" class="img-rounded img-responsive" />  -->
                    </div>
                    <div class="col-sm-6 col-md-8">
                        <h4><%= @employee.name %></h4>
                        <small><cite title="<%= @employee.address %>"><%= @employee.address %><i class="glyphicon glyphicon-map-marker">
                        </i></cite></small>
                        <p>
                            <i class="glyphicon glyphicon-envelope"></i><%= @employee.email %>
                            <br />
                            <i class="fa fa-transgender"></i> <%= @employee.gender %>                            
                            <br />
                            <i class="glyphicon glyphicon-gift"></i><%= @employee.dob %></p>

                    </div>
                </div>
                <%= link_to "Edit", edit_employee_path(@employee) , class: "btn btn-large btn-primary"%>
                <%= link_to "Delete", @employee, method: :delete, data: { confirm: "Are You Sure?"}, class: "btn btn-large btn-primary"%>

        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Built with <i class="fa fa-heart"></i> by Nkulukeo Mokgele
    </small>
    <ul>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact Me", contact_path %></li>
        <li><a href="https://www.thedigitalacademy.co.za" target="_blank">Digital Academy</li>
    </ul>
</footer>

app/views/layouts/_head.html.erb
    <title><%= full_title(yield(:title))%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">     
        <%= link_to "EMS", root_path, id: "logo"%>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Employees", employees_path %></li>
            <li><%= link_to "Help", help_path %></li>
          </ul>
        </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!-- [if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
<! [endif] -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="center jumbotron">  
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}")%>
        <% end %>
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @employee.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
        The Form Contains <%= pluralize(@employee.errors.count, "error") %>
    </div>
    <ul>
        <% @employee.errors.full_messages.each do | message | %>
            <li><%= message %></li>
        <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About')%>
<h1>About</h1>
<p>About page for Employee Management System</p>
<img src="https://cdn.pixabay.com/photo/2017/08/20/17/42/gulls-2662550_1280.jpg" alt="gulls" class="img-rounded img-responsive">

app/views/static_pages/contact.html.erb
<%= provide(:title, 'Contact')%>
<h1>Contact</h1>
<p>Contact page for Employee Management System</p>
                        <h4>Nkululeko Mokgele</h4>
                        <hr>
                        <p>
                            <i class="glyphicon glyphicon-envelope"></i>nmokgele@gmail.com
                            <br />
                            <i class="fa fa-github"></i> <a href="https://github.com/nmabe" target="_blank" >nmabe</a>                            
                            <br />
                            <i class="glyphicon glyphicon-earphone"></i>065 901 8407</p>
                        </p>

app/views/static_pages/help.html.erb
<%= provide(:title, 'Help')%>
<h1>Help</h1>
<p>Help page for Employee Management System</p>

app/views/static_pages/home.html.erb
<%= provide(:title, 'Home')%>
<h1>Employee Management System</h1>
<p>This is the home page of the Employee Management System</p>
<%= link_to "Create New Employee", new_path , class: "btn btn-large btn-primary"%>
<%= link_to "View Employees", employees_path , class: "btn btn-large btn-primary"%>